name: Run Tests

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run Unit Tests
        run: mvn clean test
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unit-tests